classDiagram
class IPlayer{
    <<interface>>
    +int id
    +String name
}
class Player{
    +int id
    +String name
    +Player(int id, string name)
}
class ICard{
    <<interface>>
    +int id
    +int firstFaceValue
    +int secondFaceValue 
}
class IDisplay {
    +ShowBoard(List~Card~ board) : void
    +ShowHand(List~Card~ hand) : void
}
class IDeck{
    <<interface>>
    +Shuffle() : void
    +DrawCard() : Card
}
class IBoard{
    <<interface>>
    +UpdateBoard(Card card, IPlayer player) : void
    +GetBoard() : List~Card~
}
class Deck{
    -List~ICard~ cards
    +Shuffle() : void
    +DrawCard() : ICard
}
class Board{
    -List~ICard~ playedCards
    +UpdateBoard(ICard card, IPlayer player) : void
    +GetBoard() : List~ICard~
}
class Card{
    +int id
    +int firstFaceValue
    +int secondFaceValue   
    +IsDouble() : bool
}
class GameController{
    -IDeck deck
    -IBoard board
    -List~IPlayer~ players
    -Dictionary~IPlayer, List_Card~ hand
    -Dictionary~int, Card~ moveOptions
    -IPlayer currentPlayer
    -int maxPlayers
    -Action onGameStart
    -Action~IPlayer~ onPlayerTurn
    -Action~bool~ onGameOver
    +GetValue(Card card) : int
    +GetScore(IPlayer player)
    +StartGame(Action onGameStart)
    +NextTurn(Action~IPlayer~ onPlayerTurn)
    +PassTurn() : void
    +ValidateMove(Func~bool~ isGameOver) : bool
    +GetWinner() : IPlayer
    +GetPlayableMoves(IPlayer player) : Dictionary~int, Card~
    +ExecuteMove(int option) : bool
    +SetupPlayers(int playerCount) : bool
    +AssignPlayerNames() : void
    +DetermineFirstPlayer() : IPlayer
    +TurnOrder() : void
    +CheckGameOver() : bool
}
IPlayer --o GameController : aggregation
IDeck ..> GameController
IBoard ..> GameController
Deck --|> IDeck
Board --|> IBoard
Player --|> IPlayer
ICard --o Deck : aggregation
ICard <-- Board
IDisplay o.. GameController
ICard <|.. Card